### ISSUE TITLE
PISCES

### ISSUE THREAD

**Issue by jagoosw** [OceanBioME/OceanBioME.jl#44]
Having been worrying about what dynamic elements we're missing with such a simple model as LOBSTER I've started coding up PISCESv2. It is very complicated with a lot of tracers so may take me a while.

Even if we don't use it much it will be helpful to compare LOBSTER to and is helping me to understand the more complex elements of biogeochemistry. It will also be good to have the gold standard biogeochemical model available for other people to use/improve in the future.

**Comment by Atreyu-94** [comment]
Is this still under consideration?

**Comment by jagoosw** [comment]
Closed by #178

**Comment by jagoosw** [comment]
Hey @Atreyu-94,

Just to let you know, we've just merged a working version of PISCES into main.

We haven't been able to validate it against the Fortran implementations yet but plan on doing it soon.

**Comment by Atreyu-94** [comment]
Thank you very much for letting me know! It's still not documented, right?
